service: borken-bot

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage, 'production'}

  region: us-east-1

  iamRoleStatements:
  -  Effect: "Allow"
     Action:
       - "s3:*"
     Resource:
       - "arn:aws:s3:::${file(.config.json):output_bucket}/*"

  environment:
    C_KEY: ${file(.config.json):consumer_key}
    C_SECRET: ${file(.config.json):consumer_secret}
    A_KEY: ${file(.config.json):access_key}
    A_SECRET: ${file(.config.json):access_secret}
    MapboxAccessToken: ${file(.config.json):mapbox_token}
    OUTPUT_BUCKET: ${file(.config.json):output_bucket}

  deploymentBucket: ${file(.config.json):output_bucket}

package:
  artifact: package.zip

functions:
  bot:
    handler: handler.handler
    memorySize: 1536
    timeout: 20
    events:
      - schedule: rate(1 hour)
